[main]
shell=/usr/bin/zsh

[scrollback]
lines=10000
multiplier=3.0
indicator-position=none

[cursor]
style=block
blink=yes

[colors-dark]
# Latar belakang hitam pekat agar kontras teks maksimal
background=000000
# Teks utama putih bersih agar tidak redup oleh gamma 0.7
foreground=ffffff
# Kursor: teks dalam kursor hitam (000000), blok kursor putih (ffffff)
cursor=000000 ffffff
# Indikator posisi scroll (teks hitam di pill biru terang)
scrollback-indicator=000000 7aa2f7

## Warna Reguler (Warna Dasar)
regular0=333333  # Hitam abu-abu
regular1=ff3333  # Merah solid (tajam)
regular2=33ff33  # Hijau terang
regular3=ffaa00  # Oren hangat
regular4=55ffff  # Biru diganti Cyan/Sian (hijau-biru terang)
regular5=ff55ff  # Magenta/Merah muda terang
regular6=ffff55  # Kuning terang
regular7=ffffff  # Putih

## Warna Bright (Warna Intensitas Tinggi)
bright0=555555   # Abu-abu terang
bright1=ff6666   # Merah neon
bright2=66ff66   # Hijau neon
bright3=ffbb33   # Oren terang (sangat terlihat)
bright4=aaffff   # Cyan muda (putih kebiruan)
bright5=ff88ff   # Magenta muda
bright6=ffff99   # Kuning muda (putih kekuningan)
bright7=ffffff   # Putih maksimal

[url]
launch=xdg-open ${url}
# Regex POSIX valid untuk mendeteksi ekstensi file & URL
regex=([a-zA-Z0-9_.-]+\.(md|txt|sh|py|js|json|yaml|yml|rs|go)|(https?|ftp|file)://[^[:space:]()<>]+)
label-letters=sadfjklewcmpgh
# Memberi garis bawah otomatis pada link/path yang terdeteksi
osc8-underline=always
